project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio_1.qmd
        text: Aircraft Delay Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual